//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose BatPose
        {
            get
            {
                return SteamVR_Actions.default_BatPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean SetFlyingReference
        {
            get
            {
                return SteamVR_Actions.default_SetFlyingReference;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fly
        {
            get
            {
                return SteamVR_Actions.default_Fly;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
